### ISSUE TITLE
Widget breaks when name like Model[Field]

### ISSUE THREAD

**Issue by tahpot** [DevGroup-ru/yii2-ace-widget#3]
If you are using Yii2 ActiveField's, then field names are in the format Model[Field].

If you specify a name in that format, it breaks jQuery and Ace doesn't load.

I suggest fixing with the addition of double quotes around $this->name as follows:

Line 28: AceInput.php
>            "$('textarea[name=\"{$this->name}\"').each(function(index, element) {

**Comment by evgen-d** [comment]
please, check with last commit

**Comment by tahpot** [comment]
Thanks -- fixed some other issues in the process too.
